### ISSUE TITLE
Is it able to mount and goto the mount point using one single binding?

### ISSUE THREAD

**Issue by c02y** [boydaihungst/simple-mtpfs.yazi#1]
If not possible currently, it is recommended to combine these two functions or create a new function to combine these two functions.

Other suggestions:
1. `select-then-mount`, auto mount the device if there is only one device listed, so we don't have to choose the device manually
2. `select-then-unmount`, auto umount the currently mounted device if there is only one device mounted.
3. `jump-to-device`, auto jump to the mounted device if there is only one device mounted.

**Comment by boydaihungst** [comment]
Done in https://github.com/boydaihungst/simple-mtpfs.yazi/commit/5b8a91096f95b1e74c1c0c3a2a5330dd08d80eea

**Comment by boydaihungst** [comment]
now you can use `jump` in args to auto goto mountpoint after mounting new device: 
`{ on = [ "M", "m" ], run = "plugin simple-mtpfs --args='select-then-mount --jump'", desc = "Select device then mount" },`
