### ISSUE TITLE
[Feature Quest] Remount the current device

### ISSUE THREAD

**Issue by c02y** [boydaihungst/simple-mtpfs.yazi#3]
When I mount my mtp device which is an eink reader, after I transfer a file into the mtp device, if I open the file in my mtp device without unplugging the USB wire, the mtp device is somehow got disconnected without any notification, so when try to copy another file into the mtp device inside yazi, it fails, I have to cd into my local folder(stay out of the mounted path) and remount it, this happens as well when I delete a file in the mtp device, but the file list in yazi stay unchanged.

I use a GUI file manager to manage files between mtp device and my computer before using this yazi plugin, it happens in GUI manager as well, it got disconnected quite often once I open a file in it. I made a bookmark in the GUI file manager, once I notice it is disconnected, I click the bookmark, and it will remount the device and load the folder I need.

so my feature quest is a function/keymap to remount the mtp in place, which means, umount/mount and mtp device and cd into the current automatically, just like refreshing the directory.

**Comment by boydaihungst** [comment]
Sure. I'll add it later. 👍

**Comment by boydaihungst** [comment]
Done: https://github.com/boydaihungst/simple-mtpfs.yazi/commit/4941d8f211b620bff3b11d17add6c2f5ccd3781e

This will remount device under cwd 
(e.g. cwd = $HOME/Media/1_ZTEV5/Downloads/, device mountpoint = $HOME/Media/1_ZTEV5/)

```
{ on = [ "M", "r" ], run = "plugin simple-mtpfs --args=remount-current-cwd-device", desc = "Remount device under cwd" }
```
